### DISCUSSION TITLE
Unable to load the schema

### DISCUSSION THREAD

**Discussion by mobiqa** [learndevopsonline/learndevopsonline#494] [Q&A]
Hi Raghu,

I've been facing an issue while loading the schema in catalogue module. Can you please help me to move forward with.

![image](https://user-images.githubusercontent.com/121882538/231055320-9e929b3a-5d2a-44f6-80db-c0fd261620c0.png)

**Comment by r-devops** [comment]
Load schema change the code from this

```
- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.mobiqa.online
    file: "/app/schema/{{component}}.js"
    idempotent: yes
```

to 

```
- name: Load Schema
   ansible.builtin.shell: mongo --host mongodb-dev.mobiqa.online </app/schema/{{component}}.js
```

It will work.

**Reason for failing: Because the MongoDB module is been updated in ansible breaking the automation.**
